#!/usr/bin/env python
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Script to create a Kubernetes cluster using KubernetesClusterManager.

from vss_lib.cloud.k8s import KubernetesClusterManager

PATH_KIND_CONFIG = "/usr/local/lib/python3.12/site-packages/vss_lib/cloud/k8s/kind-config.yaml"

if __name__ == "__main__":
    manager = KubernetesClusterManager(cluster_name='test-cluster', config_file=f"{PATH_KIND_CONFIG}")
    manager.create_cluster()
    manager.list_nodes()
