name: Python PEP8 Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run flake8 PEP8 Check
      run: |
        flake8 . --output-file=flake8-report.txt

    - name: Upload flake8 report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: flake8-report
        path: flake8-report.txt
